src/com/tyust/entity/CartItem.java
package com.tyust.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class CartItem implements Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String cartItemId;//主键，条目id
	private int quantity;  //数量
	private Book book;  //条目图书
	private User user;  //条目用户
	
	//添加小计方法
	//用BigDecimal计算不会有误差
	public double getSubtotal(){
		BigDecimal b1 = new BigDecimal(book.getCurrPrice()+"");
		BigDecimal b2 = new BigDecimal(quantity+"");
		BigDecimal b3 = b1.multiply(b2);
		return b3.doubleValue();
	}
	public String getCartItemId() {
		return cartItemId;
	}
	public void setCartItemId(String cartItemId) {
		this.cartItemId = cartItemId;
	}
	public int getQuantity() {
		return quantity;
	}
	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}
	public Book getBook() {
		return book;
	}
	public void setBook(Book book) {
		this.book = book;
	}
	public User getUser() {
		return user;
	}
	public void setUser(User user) {
		this.user = user;
	}
	
	@Override
	public String toString() {
		return "CartItem [cartItemId=" + cartItemId + ", quantity=" + quantity + ", book=" + book + ", user=" + user
				+ "]";
	}
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((book == null) ? 0 : book.hashCode());
		result = prime * result + ((cartItemId == null) ? 0 : cartItemId.hashCode());
		result = prime * result + quantity;
		result = prime * result + ((user == null) ? 0 : user.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CartItem other = (CartItem) obj;
		if (book == null) {
			if (other.book != null)
				return false;
		} else if (!book.equals(other.book))
			return false;
		if (cartItemId == null) {
			if (other.cartItemId != null)
				return false;
		} else if (!cartItemId.equals(other.cartItemId))
			return false;
		if (quantity != other.quantity)
			return false;
		if (user == null) {
			if (other.user != null)
				return false;
		} else if (!user.equals(other.user))
			return false;
		return true;
	}
	
}

src/com/tyust/entity/Order.java
package com.tyust.entity;

import java.io.Serializable;
import java.util.List;

public class Order implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String oid;
	private String ordertime;
	private double total;
	private int status;//订单状态：1，未付款 2，已付款未发货 3，已发货未确认收货 4，确认收货交易成功 5，已取消
	private String address;
	private User owner;//订单拥有者
	private List<OrderItem> orderItemList;
	
	public List<OrderItem> getOrderItemList() {
		return orderItemList;
	}
	public void setOrderItemList(List<OrderItem> orderItemList) {
		this.orderItemList = orderItemList;
	}
	public String getOid() {
		return oid;
	}
	public void setOid(String oid) {
		this.oid = oid;
	}
	public String getOrdertime() {
		return ordertime;
	}
	public void setOrdertime(String ordertime) {
		this.ordertime = ordertime;
	}
	public double getTotal() {
		return total;
	}
	public void setTotal(double total) {
		this.total = total;
	}
	public int getStatus() {
		return status;
	}
	public void setStatus(int status) {
		this.status = status;
	}
	public String getAddress() {
		return address;
	}
	public void setAddress(String address) {
		this.address = address;
	}
	public User getOwner() {
		return owner;
	}
	public void setOwner(User owner) {
		this.owner = owner;
	}
	@Override
	public String toString() {
		return "Order [oid=" + oid + ", ordertime=" + ordertime + ", total=" + total + ", status=" + status
				+ ", address=" + address + ", owner=" + owner + "]";
	}
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((address == null) ? 0 : address.hashCode());
		result = prime * result + ((oid == null) ? 0 : oid.hashCode());
		result = prime * result + ((ordertime == null) ? 0 : ordertime.hashCode());
		result = prime * result + ((owner == null) ? 0 : owner.hashCode());
		result = prime * result + status;
		long temp;
		temp = Double.doubleToLongBits(total);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Order other = (Order) obj;
		if (address == null) {
			if (other.address != null)
				return false;
		} else if (!address.equals(other.address))
			return false;
		if (oid == null) {
			if (other.oid != null)
				return false;
		} else if (!oid.equals(other.oid))
			return false;
		if (ordertime == null) {
			if (other.ordertime != null)
				return false;
		} else if (!ordertime.equals(other.ordertime))
			return false;
		if (owner == null) {
			if (other.owner != null)
				return false;
		} else if (!owner.equals(other.owner))
			return false;
		if (status != other.status)
			return false;
		if (Double.doubleToLongBits(total) != Double.doubleToLongBits(other.total))
			return false;
		return true;
	}
	

}

src/com/tyust/web/OrderController.java
package com.tyust.web;

import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Properties;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;

import com.tyust.entity.CartItem;
import com.tyust.entity.Order;
import com.tyust.entity.OrderItem;
import com.tyust.entity.User;
import com.tyust.pager.PageBean;
import com.tyust.service.CartItemService;
import com.tyust.service.OrderService;
import com.tyust.util.commons.CommonUtil;
import com.tyust.util.payment.PaymentUtil;
@Controller
@RequestMapping("/order")
public class OrderController{
	@Autowired
	private OrderService orderService;
	@Autowired
	private CartItemService cartItemService;
	
	private int getPc(HttpServletRequest request){
		int pc = 1;
		String param = request.getParameter("pc");
		if(param!=null && !param.trim().isEmpty()){
			try{
				pc = Integer.parseInt(param);
			}catch(RuntimeException e){ }
		}
		return pc;
	}
	
	private String getUrl(HttpServletRequest request){
		String url = request.getRequestURI()+"?"+request.getQueryString();
		int index = url.lastIndexOf("&pc=");
		if(index!=-1){
			url = url.substring(0, index);
		}
		return url;
	}
	
	@RequestMapping("/paymentPre.do")
	public String paymentPre(ModelMap map,String oid){
		map.addAttribute("order", orderService.load(oid));
		return "/jsps/order/pay";
	}
	
	/**
	 * 支付方法
	 * @param req
	 * @param resp
	 * @return
	 * @throws ServletException
	 * @throws IOException
	 */
	@RequestMapping("/payment.do")
	public String payment(String oid,String total,String yh) throws IOException{
		Properties props = new Properties();
		props.load(this.getClass().getClassLoader().getResourceAsStream("payment.properties"));
		/*
		 * 1. 准备13个参数
		 */
		String p0_Cmd = "Buy";//业务类型，固定值Buy
		String p1_MerId = props.getProperty("p1_MerId");//商号编码，在易宝的唯一标识
		String p2_Order = oid;//订单编码
		String p3_Amt = "0.01";//支付金额    total
		String p4_Cur = "CNY";//交易币种，固定值CNY
		String p5_Pid = "";//商品名称
		String p6_Pcat = "";//商品种类
		String p7_Pdesc = "";//商品描述
		String p8_Url = props.getProperty("p8_Url");//在支付成功后，易宝会访问这个地址。
		String p9_SAF = "";//送货地址
		String pa_MP = "";//扩展信息
		String pd_FrpId = yh;//支付通道
		String pr_NeedResponse = "1";//应答机制，固定值1
		
		/*
		 * 2. 计算hmac
		 * 需要13个参数
		 * 需要keyValue
		 * 需要加密算法
		 */
		String keyValue = props.getProperty("keyValue");
		String hmac = PaymentUtil.buildHmac(p0_Cmd, p1_MerId, p2_Order, p3_Amt,
				p4_Cur, p5_Pid, p6_Pcat, p7_Pdesc, p8_Url, p9_SAF, pa_MP,
				pd_FrpId, pr_NeedResponse, keyValue);
		
		/*
		 * 3. 重定向到易宝的支付网关
		 */
		StringBuilder sb = new StringBuilder("https://www.yeepay.com/app-merchant-proxy/node");
		sb.append("?").append("p0_Cmd=").append(p0_Cmd);
		sb.append("&").append("p1_MerId=").append(p1_MerId);
		sb.append("&").append("p2_Order=").append(p2_Order);
		sb.append("&").append("p3_Amt=").append(p3_Amt);
		sb.append("&").append("p4_Cur=").append(p4_Cur);
		sb.append("&").append("p5_Pid=").append(p5_Pid);
		sb.append("&").append("p6_Pcat=").append(p6_Pcat);
		sb.append("&").append("p7_Pdesc=").append(p7_Pdesc);
		sb.append("&").append("p8_Url=").append(p8_Url);
		sb.append("&").append("p9_SAF=").append(p9_SAF);
		sb.append("&").append("pa_MP=").append(pa_MP);
		sb.append("&").append("pd_FrpId=").append(pd_FrpId);
		sb.append("&").append("pr_NeedResponse=").append(pr_NeedResponse);
		sb.append("&").append("hmac=").append(hmac);
		
		return "redirect:"+sb.toString();
	}
	
	/**
	 * 回馈方法
	 * 当支付成功时，易宝会访问这里
	 * 用两种方法访问：
	 * 1. 引导用户的浏览器重定向(如果用户关闭了浏览器，就不能访问这里了)
	 * 2. 易宝的服务器会使用点对点通讯的方法访问这个方法。（必须回馈success，不然易宝服务器会一直调用这个方法）
	 * @param req
	 * @param resp
	 * @return
	 * @throws ServletException
	 * @throws IOException
	 */
	@RequestMapping("/back.do")
	public String back(HttpServletRequest req, HttpServletResponse resp)
			throws IOException {
		/*
		 * 1. 获取12个参数
		 */
		String p1_MerId = req.getParameter("p1_MerId");
		String r0_Cmd = req.getParameter("r0_Cmd");
		String r1_Code = req.getParameter("r1_Code");
		String r2_TrxId = req.getParameter("r2_TrxId");
		String r3_Amt = req.getParameter("r3_Amt");
		String r4_Cur = req.getParameter("r4_Cur");
		String r5_Pid = req.getParameter("r5_Pid");
		String r6_Order = req.getParameter("r6_Order");
		String r7_Uid = req.getParameter("r7_Uid");
		String r8_MP = req.getParameter("r8_MP");
		String r9_BType = req.getParameter("r9_BType");
		String hmac = req.getParameter("hmac");
		/*
		 * 2. 获取keyValue
		 */
		Properties props = new Properties();
		props.load(this.getClass().getClassLoader().getResourceAsStream("payment.properties"));
		String keyValue = props.getProperty("keyValue");
		/*
		 * 3. 调用PaymentUtil的校验方法来校验调用者的身份
		 *   >如果校验失败：保存错误信息，转发到msg.jsp
		 *   >如果校验通过：
		 *     * 判断访问的方法是重定向还是点对点，如果要是重定向
		 *     修改订单状态，保存成功信息，转发到msg.jsp
		 *     * 如果是点对点：修改订单状态，返回success
		 */
		boolean bool = PaymentUtil.verifyCallback(hmac, p1_MerId, r0_Cmd, r1_Code, r2_TrxId,
				r3_Amt, r4_Cur, r5_Pid, r6_Order, r7_Uid, r8_MP, r9_BType,
				keyValue);
		if(!bool) {
			req.setAttribute("code", "error");
			req.setAttribute("msg", "无效的签名，支付失败！（你不是好人）");
			return "/jsps/msg";
		}
		if(r1_Code.equals("1")) {
			orderService.updateStatus(r6_Order, 2);
			if(r9_BType.equals("1")) {
				req.setAttribute("code", "success");
				req.setAttribute("msg", "恭喜，支付成功！");
				return "/jsps/msg";				
			} else if(r9_BType.equals("2")) {
				resp.getWriter().print("success");
			}
		}
		return null;
	}
	
	@RequestMapping("/confirm.do")
	public String confirm(ModelMap map,String oid){
		int status = orderService.findStatus(oid);
		if(status!=3){
			map.addAttribute("code", "error");
			map.addAttribute("msg", "状态不对，不能确认收货！");
			return "/jsps/msg";
		}
		orderService.updateStatus(oid, 4);//设置状态为确认收货
		map.addAttribute("code", "success");
		map.addAttribute("msg", "恭喜，交易成功！");
		return "/jsps/msg";
	}
	
	@RequestMapping("/cancel.do")
	public String cancel(ModelMap map,String oid){
		int status = orderService.findStatus(oid);
		if(status!=1){
			map.addAttribute("code", "error");
			map.addAttribute("msg", "状态不对，不能取消！");
			return "/jsps/msg";
		}
		orderService.updateStatus(oid, 5);//设置状态为取消
		map.addAttribute("code", "success");
		map.addAttribute("msg", "您的订单已取消成功！");
		return "/jsps/msg";
	}
	
	@RequestMapping("/load.do")
	public String load(ModelMap map,String oid,String btn)
			throws ServletException, IOException {
		Order order = orderService.load(oid);
		map.addAttribute("order", order);
		map.addAttribute("btn", btn);
		return "/jsps/order/desc";
	}
	
	@RequestMapping("/createOrder.do")
	public String createOrder(HttpServletRequest request){
		String cartItemIds = request.getParameter("cartItemIds");
		List<CartItem> cartItemList = cartItemService.loadCartItems(cartItemIds);
		//创建order
		Order order = new Order();
		order.setOid(CommonUtil.uuid());
		order.setOrdertime(String.format("%tF %<tT", new Date()));
		order.setStatus(1);
		order.setAddress(request.getParameter("address"));
		User owner = (User) request.getSession().getAttribute("sessionUser");
		order.setOwner(owner);
		BigDecimal total = new BigDecimal("0");
		for(CartItem cartItem : cartItemList){
			total = total.add(new BigDecimal(cartItem.getSubtotal()+""));
		}
		order.setTotal(total.doubleValue());
		//创建List<OrderItem>
		//一个CartItem对应一个OrderItem
		List<OrderItem> orderItemList = new ArrayList<OrderItem>();
		for(CartItem cartItem : cartItemList){
			OrderItem orderItem = new OrderItem();
			orderItem.setOrderItemId(CommonUtil.uuid());
			orderItem.setQuantity(cartItem.getQuantity());
			orderItem.setSubtotal(cartItem.getSubtotal());
			orderItem.setBook(cartItem.getBook());
			orderItem.setOrder(order);
			orderItemList.add(orderItem);
		}
		order.setOrderItemList(orderItemList);
		orderService.createOrder(order);
		//保存订单并转发
		request.setAttribute("order", order);
		//删除购物车里的生成订单的条目
		cartItemService.batchDelete(cartItemIds);
		return "/jsps/order/ordersucc";
	}
	
	@RequestMapping("/myOrders.do")
	public String myOrders(HttpServletRequest request){
		int pc = getPc(request);
		String url = getUrl(request);
		//从当前session中获取
		User user = (User) request.getSession().getAttribute("sessionUser");
		PageBean<Order> pb = orderService.myOrders(user.getUid(), pc);
		pb.setUrl(url);
		request.setAttribute("pb", pb);
		
		return "/jsps/order/list";
	}
}

WebContent/adminjsps/admin/order/desc.jsp
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title>订单详细</title>
	<meta http-equiv="content-type" content="text/html;charset=utf-8">
	<!--
	<link rel="stylesheet" type="text/css" href="styles.css">
	-->
	<link rel="stylesheet" type="text/css" href="<c:url value='/adminjsps/admin/css/order/desc.css'/>">
  </head>
  
<body>
	<div class="divOrder">
		<span>订单号：${order.oid }
        <span class="orderTime"></span>
				
<!-- 
				(准备发货)
				(等待确认)
				(交易成功)
				(已取消)
 -->
		　 下单时间：<span class="orderTime">${order.ordertime }</span>
		</span>
	</div>
	<div class="divRow">
		<div class="divContent">
			<dl>
				<dt>收货人信息</dt>
				<dd>${order.address }</dd>
			</dl>
		</div>
		<div class="divContent">
			<dl>
				<dt>商品清单</dt>
				<dd>
					<table cellpadding="0" cellspacing="0">
						<tr style="border-radius: 3px;">
							<th class="tt">商品名称</th>
							<th class="tt" align="left">单价</th>
							<th class="tt" align="left">数量</th>
							<th class="tt" align="left">小计</th>
						</tr>
                  <c:forEach items="${order.orderItemList }" var="orderItem">
						<tr style="padding-top: 20px; padding-bottom: 20px;">
							<td class="td" width="400px">
								<div class="bookname">
								  <img align="middle" width="70" src="<c:url value='/${orderItem.book.image_b }'/>"/>
								  ${orderItem.book.bname }
								</div>
							</td>
							<td class="td" >
								<span>&yen;${orderItem.book.currPrice }</span>
							</td>
							<td class="td">
								<span>${orderItem.quantity }</span>
							</td>
							<td class="td">
								<span>&yen;${orderItem.subtotal }</span>
							</td>			
						</tr>
                 </c:forEach>
																			
					</table>
				</dd>
			</dl>
		</div>
		<div class="divBtn">
			<span class="spanTotal">合　　计：</span>
			<span class="price_t">&yen;${order.total }</span><br/>
<c:if test="${order.status eq 2 and btn eq 'deliver'}">
	<a id="deliver" href="/yosebook-ssm/admin/order/deliver.do?oid=${order.oid }">发　　货</a>
</c:if>
<c:if test="${order.status eq 1 and btn eq 'cancel'}">
	<a id="cancel" href="/yosebook-ssm/admin/order/cancel.do?oid=${order.oid }">取　　消</a>
</c:if>
		</div>
	</div>
</body>
</html>


WebContent/adminjsps/admin/order/list.jsp
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title>订单列表</title>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<!--
	<link rel="stylesheet" type="text/css" href="styles.css">
	-->
<link rel="stylesheet" type="text/css"
    href="<c:url value='/jsps/pager/pager.css'/>" />
<%-- <script type="text/javascript"
    src="<c:url value='/jsps/pager/pager.js'/>"></script> --%>
<link rel="stylesheet" type="text/css"
    href="<c:url value='/adminjsps/admin/css/order/list.css'/>" />
<link rel="stylesheet" type="text/css"
    href="<c:url value='/css/css.css'/>" />

</head>

<body>
    <p class="pLink">
        <a href="<c:url value='/admin/order/findByStatus.do?status=1'/>">未付款</a>
        | <a href="<c:url value='/admin/order/findByStatus.do?status=2'/>">已付款</a>
        | <a href="<c:url value='/admin/order/findByStatus.do?status=3'/>">已发货</a>
        | <a href="<c:url value='/admin/order/findByStatus.do?status=4'/>">交易成功</a>
        | <a href="<c:url value='/admin/order/findByStatus.do?status=5'/>">已取消</a>
    </p>
    <div class="divMain">
        <div class="title">
            <div style="margin-top: 7px;">
                <span style="margin-left: 150px; margin-right: 280px;">商品信息</span>
                <span style="margin-left: 40px; margin-right: 100px;">金额</span>
                <span style="margin-left: 50px; margin-right: 53px;">订单状态</span>
                <span style="margin-left: 100px;">操作</span>
            </div>
        </div>
        <br />
        <table align="center" border="0" width="100%" cellpadding="0"
            cellspacing="0">
<c:forEach items="${pb.beanList }" var="order">
            <tr class="tt">
                <td width="320px" class="brlf">订单号：<a
                    href="<c:url value='/admin/order/load.do?oid=${order.oid }'/>">${order.oid }</a></td>
                <td width="200px">下单时间：${order.ordertime }</td>
                <td width="178px">&nbsp;</td>
                <td width="205px">&nbsp;</td>
                <td class="brrt">&nbsp;</td>
            </tr>
            <tr style="padding-top: 10px; padding-bottom: 10px;">
                <td colspan="2">
            <c:forEach items="${order.orderItemList }" var="orderItem">
                <img border="0" width="70"
                    src="<c:url value='/${orderItem.book.image_b }'/>" />
            </c:forEach>
                </td>
                <td style="padding-left: 0"><span class="price_t">&yen;${order.total }</span>
                </td>
                <td>
           <c:choose>
                <c:when test="${order.status eq 1 }">(等待付款)</c:when>
                <c:when test="${order.status eq 2 }">(准备发货)</c:when>
                <c:when test="${order.status eq 3 }">(等待确认)</c:when>
                <c:when test="${order.status eq 4 }">(交易成功)</c:when>
                <c:when test="${order.status eq 5 }">(已取消)</c:when>
            </c:choose>
                </td>
                <td>
                <a href="<c:url value='/admin/order/load.do?oid=${order.oid }'/>">查看</a><br />
            <c:if test="${order.status eq 1 }">
                <a href="<c:url value='/admin/order/load.do?oid=${order.oid }&btn=cancel'/>">取消</a><br />
            </c:if>
            <c:if test="${order.status eq 2 }">
                <a href="<c:url value='/admin/order/load.do?oid=${order.oid }&btn=deliver'/>">发货</a>
            </c:if>
                </td>
            </tr>
</c:forEach>             
        </table>
        <br />
        <%@include file="/jsps/pager/pager.jsp"%>
    </div>
</body>
</html>